apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.global.postgresql.auth.password | default "ecommerce_admin" | quote }}
  CLIENT_ID: {{ .Values.google.clientId | quote }}
  CLIENT_SECRET: {{ .Values.google.clientSecret | quote }}
